.container {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 0 auto;
  width: 400px;
  height: 100vh;
}

.header {
  background-color: #f2f2f2;
  padding: 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header .logo-image {
  width: 50px;
  height: 50px;
  border-radius: 50%;
}

.main {
  padding: 20px;
}

.section {
  display: flex;
  justify-content: space-between;
  margin-bottom: 20px;
}

.icon {
  width: 30px;
  height: 30px;
  cursor: pointer;
  transition: transform 0.2s ease-in-out;
}

.icon:hover {
  transform: scale(1.1);
}
